os:
  - linux

cache: apt

before_install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

before_script:
  - sudo add-apt-repository -y ppa:pipelight/stable
  - sudo apt-get update -qq
  - sudo apt-get install -y --install-recommends wine-staging wine-staging-compat
  - sudo apt-get install -y netcat-openbsd

language: c

compiler:
  - gcc

script:
  - wineboot
  - export STAGING_WRITECOPY=1
  - export MSYSTEM=MSYS
  - export WINEDEBUG=-all
  - pwd
  - ls
  - SCRIPT_DIR=$(pwd)
  - cd ~/.wine/drive_c
  - wget http://sourceforge.net/projects/msys2/files/Base/i686/msys2-base-i686-20150512.tar.xz
  - tar xf msys2-base-i686-20150512.tar.xz
  - wineconsole --backend=curses msys32/usr/bin/bash.exe -l -c "echo restart"
  - MSYS2_HOME=msys32/home/$USER
  - cp $SCRIPT_DIR/PKGBUILD $MSYS2_HOME
  - cp $SCRIPT_DIR/msys2_update.sh $MSYS2_HOME
  - cp $SCRIPT_DIR/msys2_socat.sh $MSYS2_HOME
  - cp $SCRIPT_DIR/build.sh $MSYS2_HOME
  - wineconsole --backend=curses msys32/usr/bin/bash.exe -l -c "./msys2_update.sh"
  - wineconsole --backend=user msys32/usr/bin/bash.exe -l -c "./msys2_socat.sh" & # msys2 socat run in background
  - echo wait until msys2 socat is ready && sleep 400
  - echo "ls -lh" | nc 127.0.0.1 44444  # test nc
  - (echo "./build.sh"; sleep 3600) | nc 127.0.0.1 44444 & # background
  - wineserver --wait # wait wine processes to prevent travis ci exiting unexpectedly
