os:
  - linux

before_install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

before_script:
  - sudo add-apt-repository ppa:pipelight/stable
  - sudo apt-get update -qq
  - sudo apt-get install -y --install-recommends wine-staging

language: c

compiler:
  - gcc

script:
  - wineboot
  - export WINEDEBUG=-all
